# Generated by Django 4.2.4 on 2023-08-27 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['id'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
    ]
