# Generated by Django 4.2.4 on 2023-08-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
